name: Build My Portfolio

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get the code
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install stuff
        run: npm install
        
      - name: Check if it builds
        run: npm run build
        
      - name: Show me what got built
        run: |
          echo "Build done! Here's what we got:"
          ls -la dist/

  docker-stuff:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Get the code again
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t apiyush296/my-portfolio:latest .
          
      - name: Test Docker container
        run: |
          echo "Testing container..."
          docker run -d --name test-portfolio -p 8080:80 apiyush296/my-portfolio:latest
          sleep 10
          docker ps
          docker stop test-portfolio
          docker rm test-portfolio
          echo "Test passed!"
          
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Pushing to Docker Hub..."
          docker push apiyush296/my-portfolio:latest
          echo "Docker image pushed!"

  check-deployment:
    needs: [build, docker-stuff]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: All good
        run: |
          echo "Everything looks good!"
          echo "✅ Build successful"
          echo "🐳 Docker image ready"
          echo "📦 Pushed to Docker Hub"
          echo "🚀 Portfolio is ready to go live!"