name: Build My Portfolio

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get the code
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install stuff
        run: npm install
        
      - name: Check if it builds
        run: npm run build
        
      - name: Show me what got built
        run: |
          echo "Build done! Here's what we got:"
          ls -la dist/

  check-deployment:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: All good
        run: |
          echo "Everything looks good!"
          echo "Portfolio is ready to go live 🚀"